networks:
  default:
    name: scm-network

services:
  scm-db:
    container_name: scm-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 5432:5432
    # volumes:
    #   - ./db/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=scm-db-user
      - POSTGRES_PASSWORD=scm-db-pwd
      - POSTGRES_DB=scm_db
    command:
      - 'postgres'
      - '-N'
      - '500'
  scm-backend:
    build:
      context: ../../submodules/stylus-cm-backend
      dockerfile: Dockerfile
    volumes:
      - ../../submodules/stylus-cm-backend/src:/app/src
      - ../../submodules/stylus-cm-backend/.env:/app/.env
    ports:
      - 3000:3000
      - 9229:9229
    restart: unless-stopped
    command: ['sleep', '3600']
